# Site settings
title: A Romance of Many Dimensions.
header-img: img/home-bg.png
email: torku.ae@gmail.com
copyright_name: indigotorch
description: > # this means to ignore newlines until "baseurl:"
  Come with me, as I take a software dev walk on the wild side.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  indigotorch
learn_profile: indigotorch
email_username: torku.ae@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
